<?php
$con=mysql_connect("localhost","root","");
mysql_select_db("poshakh",$con);
session_start();
$cid=$_SESSION['cid'];
$id=$_SESSION['id'];
$table=$_SESSION['table1'];
$sql1=("select * from ".$table." where p_id=".$id);
$result1=mysql_query($sql1)or die(mysql_error());
$row1=mysql_fetch_array($result1);
$d=date("Y/m/d");
$qua=$_SESSION['qua'];
$total=$qua*$row1[3];
$gst=$total*5/100;
$g_total=$gst+$total;
$sql3=("select * from customer where cust_id=".$cid);
$result3=mysql_query($sql3)or die(mysql_error());
$row3=mysql_fetch_array($result3);
$sql=("insert into bill values(default,$cid,'$row3[6]','$row3[6]','$d','$d',$id,$qua,$row1[3],$gst,$total,$g_total)");
mysql_query($sql);
$i=mysql_insert_id();
$sql4=("select * from bill where bill_id=".$i);
$result4=mysql_query($sql4)or die(mysql_error());
$row4=mysql_fetch_array($result4);
echo "<link rel='stylesheet' href='input.css'>";
echo "<div style='border:2px solid black; margin-top:60px; margin-left:400px; height:635px; width:700px;margin-right:500px'>";
echo "<h1 style='margin-left:250px'>Purchase bill</h1>";
echo "<h2 style='margin-left:50px'><i><b>Sold By : </b> POSHAKH.com</h2></i>";
echo "<h5 style='margin-left:50px'><b>  Warehouse Address :</b> </h5>";
echo "<h3 style='margin-left:50px'><i>Order Id:".$row4[0]." </i></h3>";
echo "<h3 style='margin-left:50px'><i>Billing Address :".$row4[2]." </i></h3>";
echo "<h3 style='margin-left:50px'><i>Shipping Address : ".$row4[3]."</i></h3>";
echo "<h3 style='margin-left:50px'><i>Order Date : ".$row4[4]." </i></h3>";
echo "<h3 style='margin-left:50px'><i>Invoice Date :".$row4[5]."</i></h3>";
echo "<h3 style='margin-left:50px'><i>Product Name :".$row1[1]." </i></h3>";
echo "<h3 style='margin-left:50px'><i>Quantity : ".$row4[7]."</i></h3>";
echo "<h3 style='margin-left:50px'><i>Price : ".$row4[8]."</i></h3>";
echo "<h3 style='margin-left:50px'><i>Total : ".$row4[10]."</i></h3>";
echo "<h3 style='margin-left:50px'><i>GST(5%) : ".$row4[9]."</i></h3>";
echo "<h2 style='margin-left:50px'><i>Grand Total : ".$row4[11]."</i></h2>";
echo "<h7 style='margin-left:50px'><i>will deliver in 5-6 days.</i></h7>";
echo "</div>";
echo "<a href='Home.php' style='width:150px; background-color: #FF5733; border: none;  color: white; margin-top:10px; padding: 15px;  text-align: center;  text-decoration: none; margin-left:660px; display: inline-block;  font-size: 20px;  cursor: pointer;border-radius:3px;' >OKAY</a>";
?>